<?php
$names = array("Touf",
"Théophile",
"Théophile Delmas",
"Delmas",
"Osklau Saint-Léger",
"Osklau",
"O. S. L.",
"thdelmas",
"Jerry Gaulé",
"Jerry",
"Mía",
"Jerry",
"thdelmas",
"Delmas",
"Mía",
"thdelmas",
"Mía",
"Jerry",
"Mía",
"thdelmas",
"Mía More");

$name = $names[array_rand($names)];

if (strpos($name, ' ') === false) {
	$titles = array("[DEPRECATED] " . $name,
	"Chaotic Good",
	"Someone Else Broke It",
	"That Guy",
	"Jack Sparrow",
	"A Mentor",
	"Segfault Witness",
	"Code stabber",
	"iMac Gyver",
	"iMacs Giver",
	"Gringo",
	"Where there is a shell, there is a way",
	"🧸",
	"Les aventures de " . $name,
	"Majin " . $name,
	"Hitchhiker " . $name,
	"Boring Startuper " . $name,
	"serial ReDumper " . $name,
	"Randomly pop " . $name,
	"Grandpa " . $name,
	"Drama queen " . $name,
	"🪖 Fast & Furious, " . $name,
	"Philosopher " . $name,
	"Libra, " . $name,
	"Enxaneta, Rebel, " . $name,
	"Shell Guru " . $name,
	"The true and only " . $name,
	"Maître de l'évasion " . $name,
	"Pentester " . $name,
	"✨⭐️✨ Who needs a 🖥 to code? Not " . $name . " ! ✨⭐️✨",
	"🐧 Kernel Panic " . $name . " 💥",
	"Dompteur d'abeilles " . $name . " 🐝",
	"🚀 " . $name . " 🚀",
	"Sacré " . $name,
	"Exam breaker " . $name,
	"Exam fixer " . $name,
	"Challenger " . $name,
	"Coalition Master " . $name,
	"Tetris Master " . $name,
	"Bounty Hunter " . $name,
	"Googler " . $name,
	"El " . $name,
	"Master of time " . $name,
	"Pokemon Master " . $name,
	"Happy " . $name . " 🐝",
	"Quarantine Specialist " . $name,
	"Old Big Brain " . $name,
	"New Big Brain " . $name,
	"Core Contributor " . $name,
	"Wesh " . $name,
	"Socrate *" . $name,
	"Poète, " . $name,
	"Guardian of the Galaxy " . $name,
	"Altruist " . $name,
	"Man in the middle " . $name,
	"one_man_army_" . strtolower($name) . ".h",
	"Awesome " . $name,
	"Squatter " . $name,
	"🔥 " . $name . " was here before air conditioning 🔥",
	"🐣 Mentor " . $name . " 🐥",
	"🐣 Babysitter " . $name . " 🐥",
	"✨" . $name . "✨",
	"L'inarrêtable " . $name . " 🌪️",
	"Fs0ci3ty " . $name,
	"Dark Army " . $name,
	"Jailbreaker " . $name,
	"Photographe " . $name,
	"Casse noisettes " . $name,
	"Balle Perdue " . $name,
	"Gratteur " . $name,
	"Player " . $name,
	"Driver " . $name,
	"Gitan " . $name,
	"Crazy " . $name,
	"Ghostbuster " . $name,
	"Limitless " . $name,
	"Cuistot " . $name,
	"Magic " . $name,
	"Tetris Challenger " . $name,
	"El Padre " . $name,
	"Le mythe du stagiaire SI qui cassait l'intra était donc vrai, il s'agit de " . $name,
	strtolower($name) . ".sh",
	strtolower($name) . ".dev",
	strtolower($name) . ".world",
	$name . ", Commander of the Night's Watch 🦝",
	$name . ", git touristique",
	$name . ", ☁️ Cloud Architect",
	$name . " Floorwalker",
	$name . " du voyage",
	$name . ", the Excel Nerd",
	$name . ", the machinist",
	$name . ", Google shits",
	$name . ", le touriste",
	$name . ", The Renegade",
	$name . ", moving through mines and bugs",
	$name . ", chica del Cable",
	$name . ", student @ 42 Barcelona",
	$name . ", root @ 42 Barcelona",
	$name . "Ã©crit en UTF-8",
	$name . ", l'ami des animaux",
	$name . " the dog charmer",
	$name . ", the Answer",
	$name . ", chef crêpier",
	$name . ", Dreamer 42",
	$name . " au chocolat 🍫",
	$name . " the All-Seeing Eye",
	$name . " is love ❤️ ",
	$name . ", como la navidad ❄️ ",
	$name . " la petite sorcière 🧹",
	$name . ", the World-bearing Turtle",
	$name . ", le bricoleur 🔧",
	$name . ", the Total Recall",
	$name . ", le seul et l'unique",
	$name . ", the pedago-guy",
	$name . " voyage voyage",
	$name . " --posix",
	$name . "-sama",
	$name);
	$name = $titles[array_rand($titles)];
}
?>

<?php echo $name ; ?>
